GET http://localhost:3001/user/myUser

###

POST http://localhost:3001/user/createUser
content-type: application/json

{
    "userName": "Zilahi Istvan",
    "icon": "img"
}

###

GET http://localhost:3001/comments/data

###

POST http://localhost:3001/comments/create
content-type: application/json

{
    "icon": "img3",
    "name": "Sáfrány Emese",
    "description": "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
    "createdAt": "42 minutes ago"
}

###

PUT http://localhost:3001/comments/update/63ee91ab925d7a3ef5a38644
content-type: application/json

{
    "vote": 1
}

###

DELETE http://localhost:3001/comments/delete/63ef5808e9136f4e93518254