const Data = [
  {
    id: 1,
    img: require("./imgs/diary.jpg"),
    year: "2019",
    type: "Movie",
    rating: "PG",
    title: "The Great Diary",
    itemType: "item",
    bookmarked: false,
  },
  {
    id: 2,
    img: require("./imgs/pinguin.jpg"),
    year: "2020",
    type: "Series",
    rating: "PG",
    title: "Antarctic Wildlife",
    itemType: "item",
    bookmarked: false,
  },
  {
    id: 3,
    img: require("./imgs/car.jpg"),
    year: "2012",
    type: "Series",
    rating: "E",
    title: "Hit the Gas",
    itemType: "item",
    bookmarked: false,
  },
  {
    id: 4,
    img: require("./imgs/horror.jpg"),
    year: "2021",
    type: "Movie",
    rating: "E",
    title: "Zombie At The Tombs",
    itemType: "item",
    bookmarked: false,
  },
  {
    id: 5,
    img: require("./imgs/snow_mountain.jpg"),
    year: "2017",
    type: "Series",
    rating: "E",
    title: "World's Greatest Mountains",
    itemType: "item",
    bookmarked: false,
  },
  {
    id: 6,
    img: require("./imgs/museum.jpg"),
    year: "2017",
    type: "Series",
    rating: "E",
    title: "Lost At The Museum",
    itemType: "item",
    bookmarked: false,
  },
  {
    id: 7,
    img: require("./imgs/street.jpg"),
    year: "2017",
    type: "Movie",
    rating: "E",
    title: "Helping My Past",
    itemType: "item",
    bookmarked: false,
  },
  {
    id: 8,
    img: require("./imgs/castle.jpg"),
    year: "2017",
    type: "Series",
    rating: "E",
    title: "Visitor Of New Worlds",
    itemType: "item",
    bookmarked: false,
  },
  {
    id: 9,
    img: require("./imgs/space.jpg"),
    year: "2011",
    type: "Series",
    rating: "PG",
    title: "Appearance Of Space",
    itemType: "item",
    bookmarked: false,
  },
  {
    id: 10,
    img: require("./imgs/plane.jpg"),
    year: "2018",
    type: "Series",
    rating: "E",
    title: "Reincarnation Of The Flight",
    itemType: "item",
    bookmarked: false,
  },
  {
    id: 11,
    img: require("./imgs/forrest.jpg"),
    year: "2017",
    type: "Series",
    rating: "E",
    title: "Staff Of Freedom",
    itemType: "item",
    bookmarked: false,
  },
  {
    id: 12,
    img: require("./imgs/lake.jpg"),
    year: "2010",
    type: "Series",
    rating: "PG",
    title: "Gift Of The River",
    itemType: "item",
    bookmarked: false,
  },
  {
    id: 13,
    img: require("./imgs/castle_1.jpg"),
    year: "2001",
    type: "Movie",
    rating: "PG",
    title: "Celebrate The West",
    itemType: "item",
    bookmarked: false,
  },
  {
    id: 14,
    img: require("./imgs/castle_2.jpg"),
    year: "2002",
    type: "Movie",
    rating: "PG",
    title: " Price Of The West",
    itemType: "item",
    bookmarked: false,
  },
  {
    id: 15,
    img: require("./imgs/music.jpg"),
    year: "2010",
    type: "Series",
    rating: "E",
    title: "Swindlers Of The Future",
    itemType: "item",
    bookmarked: false,
  },
  {
    id: 16,
    img: require("./imgs/art.jpg"),
    year: "2010",
    type: "Movie",
    rating: "PG",
    title: "Blinded By The Project",
    itemType: "item",
    bookmarked: false,
  },
  {
    id: 17,
    img: require("./imgs/tiger.jpg"),
    year: "2014",
    type: "Series",
    rating: "PG",
    title: "The King Of The Jungle",
    itemType: "trending",
    bookmarked: false,
  },
  {
    id: 18,
    img: require("./imgs/desert.jpg"),
    year: "2009",
    type: "Movie",
    rating: "PG",
    title: "Creatures And Guardians",
    itemType: "trending",
    bookmarked: false,
  },
  {
    id: 19,
    img: require("./imgs/countryside.jpg"),
    year: "2010",
    type: "Movie",
    rating: "PG",
    title: "Glory Of Electricity",
    itemType: "trending",
    bookmarked: false,
  },
  {
    id: 20,
    img: require("./imgs/beach.jpg"),
    year: "2001",
    type: "Movie",
    rating: "PG",
    title: "Influence Of The Ocean",
    itemType: "item",
    bookmarked: false,
  },
  {
    id: 21,
    img: require("./imgs/flowers.jpg"),
    year: "2007",
    type: "Movie",
    rating: "E",
    title: "Gift Of The Maze",
    itemType: "item",
    bookmarked: false,
  },
  {
    id: 22,
    img: require("./imgs/food.jpg"),
    year: "2017",
    type: "Movie",
    rating: "PG",
    title: "Healthy Food",
    itemType: "trending",
    bookmarked: false,
  },
  {
    id: 23,
    img: require("./imgs/friends.jpg"),
    year: "2017",
    type: "Movie",
    rating: "PG",
    title: "Intelligence Of My Friends",
    itemType: "item",
    bookmarked: false,
  },
  {
    id: 24,
    img: require("./imgs/grape.jpg"),
    year: "2000",
    type: "Series",
    rating: "PG",
    title: "Fruit Of Earth",
    itemType: "trending",
    bookmarked: false,
  },
  {
    id: 25,
    img: require("./imgs/rocks.jpg"),
    year: "1985",
    type: "Series",
    rating: "E",
    title: "Sage Of My Imagination",
    itemType: "item",
    bookmarked: false,
  },
  {
    id: 26,
    img: require("./imgs/surf.jpg"),
    year: "2023",
    type: "Series",
    rating: "E",
    title: " Staff Of The River",
    itemType: "trending",
    bookmarked: false,
  },
  {
    id: 27,
    img: require("./imgs/tree.jpg"),
    year: "2020",
    type: "Series",
    rating: "E",
    title: "Heirs Of The Gods",
    itemType: "item",
    bookmarked: false,
  },
];

export default Data;
